
    create table user_entity (
       id bigint generated by default as identity,
        created_date timestamp not null,
        display_name varchar(255),
        first_name varchar(255),
        identifier varchar(255) not null,
        last_modified_date timestamp not null,
        last_name varchar(255),
        registered boolean not null,
        user_id varchar(255) not null,
        version bigint,
        primary key (id)
    );

    alter table user_entity 
       add constraint UK_User_Identifier unique (identifier);

    alter table user_entity 
       add constraint UK_User_UserId unique (user_id);
